<?php
$_coreHelper = $this->helper('core');
$_cartHelper = $this->helper('checkout/cart');

$totalItemsInCart = $_cartHelper->getItemsCount();
$aboutUrl = Mage::helper('multipunkty')->getAboutMPSiteUrl();
?>
<?php if ($this->isVisible() AND $this->getPurchaseReward() > 0 AND $totalItemsInCart > 0): ?>
<div class="price-box">
    <?php echo $this->__('Za zakupione towary otrzymasz łącznie'); ?> <span class="regular-price"><span class="price"><?php echo ceil($_coreHelper->currency($_cartHelper->getQuote()->getGrandTotal()*$this->getPurchaseReward(), false, false)); ?> MP$</span></span>
    <br /><a href="<?php echo $aboutUrl; ?>" target="_blank"> <?php echo $this->__('Czym są MultiPunkty.pl?'); ?></a>
</div>
<?php endif; ?>