<?php $aboutUrl = Mage::helper('multipunkty')->getAboutMPSiteUrl(); ?>
<?php if ($this->isVisible() AND $this->getPurchaseReward() > 0): ?>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?php echo $this->__('Przy zakupach w naszym sklepie za każdą wydaną złotówkę otrzymujesz').' '.$this->getPurchaseReward(); ?> MP$</li>
            <li><a href="<?php echo $aboutUrl; ?>" target="_blank"> <?php echo $this->__('Zobacz czym są MultiPunkty.pl'); ?></a></li>
        </ul>
    </li>
</ul>
<?php endif; ?>